dist: trusty
addons:
  chrome: stable
  yarn: 1.6.0
os: "linux"

language: node_js
node_js:
- "14.9"

branches:
  except:
  - master

install:
- yarn install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- yarn global add codecov

script:
- yarn build:prod
- cp ./src/app/assets/README.md ./dist

deploy:
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./dist/
    target_branch: master
    on:
      branch: master